#!/bin/bash
set -ex
mkdir /tmp/unison
cd /tmp/unison
curl -fsSL -o unison.tar.gz https://github.com/bcpierce00/unison/releases/download/v2.53.0/unison-v2.53.0+ocaml-4.10.2+x86_64.linux.tar.gz
tar zxvf unison.tar.gz
mv bin/unison bin/unison-fsmonitor /usr/local/bin
chmod +x /usr/local/bin/unison*
rm -fr /tmp/unison
