#!/usr/bin/env bash
set -ex
curl -sS https://repo.saltstack.com/py3/ubuntu/20.04/amd64/latest/SALTSTACK-GPG-KEY.pub | apt-key add -
echo "deb http://repo.saltstack.com/py3/ubuntu/20.04/amd64/latest focal main" >> /etc/apt/sources.list.d/saltstack.list
apt-get update -y
apt-get install -y salt-ssh
rm -fr /var/lib/apt/lists/*
